### ISSUE TITLE
Just nothing happens

### ISSUE THREAD

**Issue by wokalek** [ijkml/nuxt-umami#75]
I install and setup module right, but it's just not send collect request on production mode. In dev mode it's sending, but i get cors (it's ok). But nothing happens in prod mode.

**Comment by ijkml** [comment]
Hello, @wokalek 
Can you provide more details? Like, what version of Umami you're using, the version of the module and a look at your module config, please.

**Comment by wokalek** [comment]
Hi @ijkml 

I use this in docker: 

```
  umami:
    container_name: wokalek-umami
    image: ghcr.io/umami-software/umami:postgresql-v2.3.0
    restart: always
    ports:
      - 3000:3000
    env_file: env/umami/.env
    depends_on:
      umami-db:
        condition: service_healthy

  umami-db:
    container_name: wokalek-umami-db
    image: postgres:15-alpine
    restart: always
    env_file: env/umami-db/.env
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
```

`env/umami/.env`
```env
DATABASE_URL = postgresql://umami:umami@umami-db:5432/umami
DATABASE_TYPE = postgresql
APP_SECRET = 123
```

`env/umami-db/.env`
```env
POSTGRES_DB = umami
POSTGRES_USER = umami
POSTGRES_PASSWORD = umami
```

`nuxt/nuxt.config.ts`

```ts

const config = {
  extends: [
    'nuxt-umami',
  ],
}
```

`nuxt/app.config.ts`

```ts
export default defineAppConfig({
  umami: {
    version: 2,
  },
})
```
